// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmuKqXXPuP8S7hmHpGKex8F4S6O20tS3Y',
    appId: '1:1078181417282:web:94c28296e0ca92c71d78db',
    messagingSenderId: '1078181417282',
    projectId: 'profilepage-project',
    authDomain: 'profilepage-project.firebaseapp.com',
    storageBucket: 'profilepage-project.appspot.com',
    measurementId: 'G-SB1CC8ZKH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmuTmOOE1UMTqD-_Opqqtj-vZaChzwxuQ',
    appId: '1:1078181417282:android:b9a796c55f4a09051d78db',
    messagingSenderId: '1078181417282',
    projectId: 'profilepage-project',
    storageBucket: 'profilepage-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRuMjuofxA36FRpSNnCPmcdkMvXNRtQ0k',
    appId: '1:1078181417282:ios:430712bc2f60c28c1d78db',
    messagingSenderId: '1078181417282',
    projectId: 'profilepage-project',
    storageBucket: 'profilepage-project.appspot.com',
    iosClientId: '1078181417282-pbt8sbhgi8bbd1p47ndgmgpe3bi9hbbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.profilePage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRuMjuofxA36FRpSNnCPmcdkMvXNRtQ0k',
    appId: '1:1078181417282:ios:61d1daec47d5563d1d78db',
    messagingSenderId: '1078181417282',
    projectId: 'profilepage-project',
    storageBucket: 'profilepage-project.appspot.com',
    iosClientId: '1078181417282-l71so0vr4ufi15lktgj4575vd0bnaa8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.profilePage.RunnerTests',
  );
}
