// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavpVbEdmMoqFWfZDDkNIsC61_wGS12cg',
    appId: '1:652896473499:web:c232913bee09239cb5d13e',
    messagingSenderId: '652896473499',
    projectId: 'profilepage-project-2cd0f',
    authDomain: 'profilepage-project-2cd0f.firebaseapp.com',
    storageBucket: 'profilepage-project-2cd0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUzr4zbM0beCtGzpZI6UcS1KhYOB-r1g0',
    appId: '1:652896473499:android:a7c7553b0ed13673b5d13e',
    messagingSenderId: '652896473499',
    projectId: 'profilepage-project-2cd0f',
    storageBucket: 'profilepage-project-2cd0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznZiW2gWAVnOStmBUcyo63yG8U0mhgrc',
    appId: '1:652896473499:ios:2cc98972cde6539db5d13e',
    messagingSenderId: '652896473499',
    projectId: 'profilepage-project-2cd0f',
    storageBucket: 'profilepage-project-2cd0f.appspot.com',
    iosClientId: '652896473499-51556fvrj3b41lcog3qvcfibtkh9loqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.profilePage',
  );
}
